name: Get Current Branch Name

on:
  push:
  pull_request:
    types:
      - closed
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  pod:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Install Pods
        working-directory: './GhActionsTest'
        run: pod install
      - name: Size cocoapods
        run: du -sh ~/.cocoapods
      - name: Size cocoapods caches
        run: du -sh ~/Library/Caches/CocoaPods
    
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: head_ref
        run: echo "${{ github.head_ref }}"
        
      - name: ref_name
        run: echo "${{ github.ref_name }}"
        
      - name: ref
        run: echo "${{ github.ref }}"

      - name: actor
        run: echo "${{ github.actor }}"

      - name: email
        run: echo "${{ github.event.pusher.email }}"

      - name: Show GitHub context   
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash
