name: Get Current Branch Name

on:
  push:
  pull_request:
    types:
      - closed
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Kotlin/Native Compiler Caches
        run: du -sh ~/.konan
      - name: Cocoapods Repository Caches
        run: du -sh ~/.cocoapods
      - name: Cocoapods Caches
        run: du -sh ~/Library/Caches/CocoaPods
        
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: head_ref
        run: echo "${{ github.head_ref }}"
        
      - name: ref_name
        run: echo "${{ github.ref_name }}"
        
      - name: ref
        run: echo "${{ github.ref }}"
