name: Merge main branch

on:
  push:
    tags:
      - v**

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  merge-main:
    name: Merge main branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: head_ref
        run: echo "${{ github.head_ref }}"
        
      - name: ref_name
        run: echo "${{ github.ref_name }}"
        
      - name: ref
        run: echo "${{ github.ref }}"
      
      - name: git
        run: |
          echo "$(git branch --show-current)"
          echo "$(git rev-parse --abbrev-ref HEAD)"
