name: Merge main branch

on:
  push:
    tags:
      - v**

permissions:
  contents: write

defaults:
  run:
    shell: bash
          
jobs:
  merge-main:
    name: Merge main branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ github.token }}
      
      - name: git
        run: |
          set -e
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin develop -v
          git checkout develop -v
          git pull origin develop -v
          git merge --no-ff --no-edit origin/main -v
          git push origin develop -v
