name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  swiftlint:
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: |
          if ! command -v swiftlint &> /dev/null
          then
            echo "SwiftLint not found."
            brew install swiftlint
          fi

      - name: Run SwiftLint
        run: swiftlint
